### ISSUE TITLE
Allow Guid to be assigned externally for Keys

### ISSUE THREAD

**Issue by ashock** [tmsmith/Dapper-Extensions#106]
I have a system where a the GUID for entities are being a supplied by external source, the default implementation for key guid columns in Dapper Extensions is generate a new guid on insert. Is it possible to change the implementation to only generate a guid if one has not been supplied when doing inserts. 
e.g. 
Change in the Inset<T>(...) methods
if (column.KeyType == KeyType.Guid)
to
if (column.KeyType == KeyType.Guid && column.PropertyInfo.GetValue(e, null) == null)

**Comment by yakrupka** [comment]
Hi checkout [https://github.com/tmsmith/Dapper-Extensions/wiki/KeyTypes](url) just map the guid to KeyType.Assigned. Do for class 
`class Foo{
public Guid Id{get;set}
...
}` you would write a Mapper
`class FooMapper:ClassMapper<Foo>{
Public FooMapper(){
Map(f=> f.Id).Key(KeyType.Assigned);
AutoMap();}
}`

**Comment by tmsmith** [comment]
Lastest version checks if Guid already is assigned.
