### ISSUE TITLE
How do you implement "IN" clause to get a set from DapperExtensions

### ISSUE THREAD

**Issue by timdooling** [tmsmith/Dapper-Extensions#109]
The predicates discussion has a "TODO" for sending in an IEnumberable<T> of predicates that should result in a selection using the "IN" clause of the WHERE statement in SQL.

The following code does not work for me:

            var predicateList = new List<Object>();

            foreach (Members_Publication publication in member_publications)
            {
               var predicate = Predicates.Field<Publication>(f => f.id, Operator.Eq, publication.publication_id);
               predicateList.Add(predicate);
            }
            using (IDbConnection dbConnection = ConnectionProvider.OpenConnection())
            {
                dbConnection.Open();
                result = dbConnection.GetList<Publication>(predicateList);
                return result;
            }
        }

What am I doing wrong here?

**Comment by MLaritz** [comment]
Make predicateList a `PredicateGroup`, and then add each predicate to the PredicateGroup.Predicates:

`var predicateList = new PredicateGroup { Operator = GroupOperator.Or, Predicates = new List<IPredicate>() };`

`predicateList.Predicates.Add(predicate);`

**Comment by rgustavsson** [comment]
I am struggeling with what seems to be the same issue,

I have a class with the following property:

`public string[] StringArray { get; set; }`

and I have a column like this:

`StringArray TEXT[]`

and my predicates looks like this:

```
pg = new PredicateGroup { Operator = GroupOperator.And, Predicates = new List<IPredicate>() };
pg.Predicates.Add(Predicates.Field<AppCalendarEvent>(f => f.TenantId, Operator.Eq, tenantId));
pg.Predicates.Add(Predicates.Field<AppCalendarEvent>(f => f.StringArray, Operator.Eq, new List<string>() { userId } ));
```

And the result of a GetPage (or GetList) is:

_Npgsql.PostgresException: '42883: operator does not exist: text[] = text'_
