### ISSUE TITLE
ClassMapper instantiation.

### ISSUE THREAD

**Issue by timglenn123** [tmsmith/Dapper-Extensions#110]
I have a custom ClassMapper<Order> and when I call connection.Insert(order) the Mapper is not instantiated.  
I saw in some other examples where it was instantiated manually, but I get null exception errors on value objects in a separate library.

 Map(o => o.OrderHeader.ShippingAddress.Contact.Name).Column("ShipToContactName");

Can I do this? It seems that if my "ShippingAddress" lives in a common library, it doesnt work. Is there a setting which I can tell DapperExtensions to look in the other assembly for the ShippingAddress object?

**Comment by tmsmith** [comment]
DapperExtension does not support this functionality.
