### ISSUE TITLE
Dapper Extensions deleted value of first foreign key in dual foreign key composite table that has no primary key.

### ISSUE THREAD

**Issue by timdooling** [tmsmith/Dapper-Extensions#112]
I have determined that DapperExtensions deletes the value of the first field containing "id" at the end even if that field is not indicated to be a primary key on an insert.

The composite key examples all show inserts with a second key, but assume identity fields for the first key.

I have an intersection data table with a composite key that has no independent primary key and, although adding one would not necessarily disrupt the data (it is a pain to clone that table data and then drop and re-add it with the primary key), we are working with an existing database that has reports generated from it independently of the application I am co-writing.

It would be very nice if DapperExtensions checked to see if the first field with "id" in it was NOT a primary key before assigning its' value to null.

After an hour of debugging, I determined this to be the problem.

Where in the source code does this happen, and can this be changed?

UPDATE:

I found the source of the problem in the routine

 protected virtual void AutoMap(Func<Type, PropertyInfo, bool> canMap)

This routine automatically assigns a key value to any field in a table with either "id" as the name (case insensitive, I assume) or ending with "id" in the name.

It is this assumption that is causing the problem.

Could this code be modified to check whether the field involved is in fact a primary key with an identity constraint before treating it as such and not writing the value supplied in the model to the insert for the field?

The system I am working with is a refactoring of a codebase originally written in Ruby on Rails and still running in an active enterprise situation where redoing the databases has a lot of potential side-effects to it.

**Comment by tmsmith** [comment]
not sure if you are still using DE and if this is a problem.  However you could override and replace the default mapper with one of your own creation.

**Comment by valfrid-ly** [comment]
It's not an issue. As AutoMap is an implementation to map automatically a object it has to make some assumptions. Think about the time consumption to go to the database, check if it has a constraint on it for example?

You can create a map for this class to solve this problem
