### ISSUE TITLE
Mapping from underscore naming.

### ISSUE THREAD

**Issue by Successful** [tmsmith/Dapper-Extensions#121]
Hi, i name my tables and columns using underscore:

this_is_a_table <-- Map to: ThisIsATable
this_is_a_column   <-- Map to: ThisIsAColumn

Dapper can handle this mapping if i set:

`DefaultTypeMap.MatchNamesWithUnderscores = true;`

Is there any way to enable this in Dapper-Extensions?

**Comment by jrc313** [comment]
You can achieve this with a custom ClassMapper. Implement a custom mapper as per the [wiki docs](../wiki/AutoClassMapper). Override the `Table` method to convert the table name and override the `AutoMap` method to convert the column names.

Something like ...

```C#
public class SnakeCaseClassMapper<T> : AutoClassMapper<T> where T : class
{
    /// <summary>
    /// Convert title case table name to snake case
    /// </summary>
    /// <param name="tableName">Title case version of the table name</param>
    public override void Table(string tableName)
    {
        this.TableName = tableName.TitleToSnakeCase();
    }

    /// <summary>
    /// Convert column names from title case to snake case.
    /// Let the base class generate the list of properties then iterate over them to
    /// convert their column names from title case to snake case.
    /// </summary>
    protected override void AutoMap()
    {
        base.AutoMap();
        foreach (var property in this.Properties)
        {
            var propertyMap = property as PropertyMap;
            if (propertyMap != null)
            {
                propertyMap.Column(property.ColumnName.TitleToSnakeCase());
            }
        }
    }
}
```

You just need to provide your own implementation of TitleToSnakeCase :smile:

**Comment by sharpe5** [comment]
This post is also enlightening: http://stackoverflow.com/questions/9350467/how-do-i-write-one-to-many-query-in-dapper-net/30080951#30080951
