### ISSUE TITLE
Insert fail : Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by hoctrokha** [tmsmith/Dapper-Extensions#123]
Hi!
I have a problem when insert a object to DB.
Here is my model:
``` CSharp
 public class Manufacturer
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public virtual IEnumerable<Product> Products { get; set; }
    }
```
and here is my insert code:
```CSharp
 using (var connection = DbConnectionManager.CreateNewConnection())
            {
                 connection.Insert(entity);
            }
```
and i got a null exception in insert statement because my Products property is null.
but Products property have no relation with DB.
how can i fix this?
thank you!

**Comment by cpayne22** [comment]
Your example doesn't make a lot of sense.  You don't mention "Product" anywhere?

See the sample code:  https://github.com/tmsmith/Dapper-Extensions#simple-insert-operation
