### ISSUE TITLE
Extentions do not work with stored procedure

### ISSUE THREAD

**Issue by monstrU** [tmsmith/Dapper-Extensions#127]
Why?
I try to use property mapping  with query. 
I am made this via ClassMapper. 
But it work only with query from table.

I want use this action to query, recieved from stored procedure.
With Query via select its work ok

var predicate = Predicates.Field<CancelledActionDateString>(f => f.Id, Operator.Eq, 46301);
var res = sqlConn.GetList<CancelledActionDateString>(predicate).ToList();

but method  sqlConn.GetList do not support stored procedure.
its very bad

**Comment by timdooling** [comment]
According to the source code, DapperExtensions generally uses the basic "Select {0} from {1}" syntax for gets.

This syntax will only work with views and tables as a general rule.

You could try using a view unless stored procedures are mandated by your system (some companies will not allow select statements to be sent to a database as an added security measure).

In case you have to use stored procedures, you can use Dapper call directly for that.  Dapper is included when you install DapperExtensions.

DapperExtensions simplifies the syntax for basic CRUD operations.

If you want more complexity, you have to use Dapper.

**Comment by tmsmith** [comment]
Dapper will map your sproc to an Entity. DapperExtensions is used to create the sql needed.
