### ISSUE TITLE
Why not returned "*" ?

### ISSUE THREAD

**Issue by TwoBee** [tmsmith/Dapper-Extensions#130]
file:SqlGenerator.cs
method :BuildSelectColumns(IClassMapper classMap)
```cs
public virtual string BuildSelectColumns()
{
    return "*";
}
```
or
```cs
public virtual string BuildSelectColumns(IClassMapper classMap)
{
    if(!classMap.ExplicitColumns) return "*";
    var columns = classMap.Properties
        .Where(p => !p.Ignored)
        .Select(p => GetColumnName(classMap, p, true));
    return columns.AppendStrings();
}
```

**Comment by tmsmith** [comment]
* would return the columns as they are named by the DB. There are time when it is necessary to return the column as a different name.  This naming is what Dapper uses to map the values to the entity.
