### ISSUE TITLE
Case Insensitive Match for Like Operator in Predicate Group

### ISSUE THREAD

**Issue by c-m-h** [tmsmith/Dapper-Extensions#134]
Hello,

Can you tell me if something like this is possible within Predicate Groups?

                    predicateGroup.Predicates.Add(Predicates.Field<Company>(p => p.company_name.ToUpper(), Operator.Like, string.Format("%{0}%", term)));

I'm getting a null reference exception on the p.company_name.ToUpper() and I wondered if there is a different syntax to achieve the result I'm expecting (where **term** is also Upper cased)

Thank you!!

**Comment by tmsmith** [comment]
This is not possible.

**Comment by c-m-h** [comment]
I had come to that conclusion as well.  Is there any way using DapperExtensions to provide case-insensitive clauses to a query?  I am unable to change any collation settings in our database (which is mySql).

Thank you.
