### ISSUE TITLE
Postgresql paging queries

### ISSUE THREAD

**Issue by kgday** [tmsmith/Dapper-Extensions#135]
Found error in code as below:

        public override string GetSetSql(string sql, int firstResult, int maxResults, IDictionary<string, object> parameters)
        {
            string result = string.Format("{0} LIMIT @firstResult OFFSET @pageStartRowNbr", sql);            
            parameters.Add("@firstResult", firstResult);
            parameters.Add("@maxResults", maxResults);
            return result;
}

line:
            string result = string.Format("{0} LIMIT @firstResult OFFSET @pageStartRowNbr", sql);            

should be

            string result = string.Format("{0} LIMIT @firstResult OFFSET @maxResults", sql);            

regards,
Kevin.

**Comment by cn181** [comment]
什么时候能支持.net core呢？

**Comment by tmsmith** [comment]
in latest
