### ISSUE TITLE
Release 1.5.0 on Nuget.org

### ISSUE THREAD

**Issue by ajukraine** [tmsmith/Dapper-Extensions#138]
When the latest release 1.5.0 would be available on Nuget.org?

My project heavily depends on packages from Nuget.org source and I'd like to use latest async/await support, so waiting for it to be available.

**Comment by tmsmith** [comment]
Look for it this week.

**Comment by ajukraine** [comment]
Thank you so much

**Comment by Boeller666** [comment]
Yes, I really need it too...
Would be fine to see the new version soon on NuGet.
