### ISSUE TITLE
SQLiteDialect prefixes column names with table name on insert

### ISSUE THREAD

**Issue by ripvannwinkler** [tmsmith/Dapper-Extensions#140]
The end result is the following SQLiteException:

SQL logic error or missing database
near ".": syntax error

An example of a generated statement with this problem:

    INSERT INTO [Keywords] ([Keywords].[Id], [Keywords].[TwitterPollInterval], [Keywords].[TwitterConsumerKey], [Keywords].[TwitterConsumerSecret], [Keywords].[TwitterAccessToken], [Keywords].[TwitterAccessSecret], [Keywords].[InstagramPollInterval], [Keywords].[InstagramClientId], [Keywords].[InstagramClientSecret], [Keywords].[InstagramAccessToken]) VALUES (@Id, @TwitterPollInterval, @TwitterConsumerKey, @TwitterConsumerSecret, @TwitterAccessToken, @TwitterAccessSecret, @InstagramPollInterval, @InstagramClientId, @InstagramClientSecret, @InstagramAccessToken)

It's clearly invalid to prefix the column names in the insert column list as SQLite is complaining here, but this code seems fairly old and stable. What am I missing?

**Comment by kelicto** [comment]
I don't know why tell this exception, because I use linq to insert data.
![image](https://user-images.githubusercontent.com/23723575/118303538-259fbc00-b518-11eb-86d8-6cd53634abea.png)
![image](https://user-images.githubusercontent.com/23723575/118303508-1caeea80-b518-11eb-9a1c-3265b00706ec.png)
![image](https://user-images.githubusercontent.com/23723575/118303193-bfb33480-b517-11eb-9804-eb77aa9e4c1c.png)

**Comment by valfrid-ly** [comment]
You need to specify the dialect.

**Comment by kelicto** [comment]
I use the extension to insert sqlite db and updated the stacktrack.
The demo url: https://github.com/kelicto/HelloDapper
The new issue: https://github.com/tmsmith/Dapper-Extensions/issues/244

**Comment by kelicto** [comment]
The extension lib is very good, I plan my project to use it. But, I must solve the problem. Could you help me to handle it, as soon as possible?
Thinks.

**Comment by valfrid-ly** [comment]
The answer is the same of this issue with PostgreSQL.

https://github.com/tmsmith/Dapper-Extensions/issues/205

**Comment by kelicto** [comment]
Thinks! It can work well! Add code: DapperExtensions.DapperExtensions.SqlDialect = new SqliteDialect();
