### ISSUE TITLE
Generated SQL exist square brackets，but mysql does not allow square brackets around table of column names

### ISSUE THREAD

**Issue by wqh21** [tmsmith/Dapper-Extensions#145]
Example:
`
conn.Insert(user);

Generated Sql:
INSERT INTO [tablename] ([tablename].[openid], [tablename].[nickname], [tablename].[sex], [tablename].[credits], [tablename].[regtime]) VALUES ('openid', '666', 1, 1.22, '2017-02-03 18:05:45.591256')
`
it's report an error in MySql5.5

**Comment by jfvoliveira** [comment]
Hi there. How did you solve this issue?

**Comment by XunWind** [comment]
You should be add line to set dialect
DapperExtensions.DapperExtensions.SqlDialect = new MySqlDialect();
