### ISSUE TITLE
如果有继承，能不能通过 加注解  来避免多余属性插入导致 错误

### ISSUE THREAD

**Issue by tkggusraqk** [tmsmith/Dapper-Extensions#156]
如果对类进行了扩展或者 继承，在插入的时候 就会报错，因为出现 了和表无法对应的字段

**Comment by zpzhangwenhan** [comment]
I dont know also !hahahhaah

**Comment by wowlc0203** [comment]
you can use a custom class mapper to ignore these field

**Comment by RookieCN** [comment]
I also want this feature

**Comment by valfrid-ly** [comment]
Acho que o problema pode ser na estrutura das classes. Eu criei classes herdadas e também herdei os mapeamentos e funciona normalmente.

Segue abaixo um exemplo da classe pai e classe filho


`namespace Examples.Base
{
    public abstract class MyBaseExample<TItem> where TItem : MyItemBase
    {
        public long Id { get; set; }
		public IEnumerable<TItem> Items { get; set; }
    }

    public abstract class MyInheritedBase<TItem> : MyBaseExample<TItem>  where TItem : MyItemBase
    {
        public string Name { get; set; }
    }

    public abstract class MyItemBase
    {
        public long Id { get; set; }
        public string Name { get; set; }
		public long ParentId { get; set; }
    }
}

namespace Examples.Implementation
{
    public class MyImplementation : MyInheritedBase<MyItemImplementation>
    {
		public string Notes { get; set; }
    }

    public class MyItemImplementation : MyItemBase
    {
		public double Value { get; set; }
    }
}


namespace Examples.Mapping
{
    public abstract class MyBaseExampleMap<T, TItem> : ClassMapper<T, MyBaseExample> 
		where T : MyBaseExample
		where TItem : MyItemBase
    {
        protected MyBaseExample() : base()
        {
            TableName = "MyTableName";

            Map(f => f.Id).Column("MyIdColumn").Key(KeyType.SequenceIdentity).Sequence("MySequence");

            Map(t => t.Items).Ignore();

            ReferenceMap(t => t.Items).Reference<TItem>((item, parent) => item.parentId == parent.id);
        }
    }

    public abstract class MyInheritedBaseMap<T, TItem> : MyBaseExample<T, MyBaseExample> 
		where T : MyBaseExample
		where TItem : MyItemBase
    {
        protected MyInheritedBase() : base()
        {
            Map(f => f.Name).Column("MyNameColumn");
        }
    }

    public abstract class MyItemBaseMap<T> : ClassMapper<T> 
		where T : MyItemBase
    {
        protected MyItemBaseMap() : base()
        {
            TableName = "MyItemTableName";

            Map(f => f.Id).Column("MyItemIdColumn").Key(KeyType.SequenceIdentity).Sequence("MySequence");
            Map(f => f.Name).Column("MyItemNameColumn");
            Map(f => f.ParentId).Column("MyFKColumn").Key(KeyType.ForeignKey);
        }
    }

    public class MyImplementationMap<MyImplementation, MyItemImplementation> : MyInheritedBaseMap<MyImplementation, MyItemImplementation> 
    {
        protected MyInheritedBase() : base()
        {
            Map(f => f.Notes).Column("MyNotesColumn");
        }
    }

    public class MyItemImplementationMap<MyItemImplementation> : MyItemBaseMap<MyItemImplementation>
    {
        protected MyInheritedBase() : base()
        {
            Map(f => f.Value).Column("MyValueColumn");
        }
    }
}
`
