### ISSUE TITLE
Dialect is set globally

### ISSUE THREAD

**Issue by robsonj** [tmsmith/Dapper-Extensions#157]
From what I can tell, the only way to set the DB dialect is using the global dapper configurator mechanism or set using...

`DapperExtensions.DapperExtensions.SqlDialect = _myDialect;`

This becomes an issue if you are executing sql against two different databases of incompatible dialect at the same time.

**Comment by tmsmith** [comment]
If you want to use multiple implementations of DapperExtensions you can try using `impl := new DapperImplementor(new SqlGeneratorImpl(config));`
