### ISSUE TITLE
OracleDialect missing in Nuget package version 1.6

### ISSUE THREAD

**Issue by Wintermute79** [tmsmith/Dapper-Extensions#161]
Using the latest Nuget package 1.6, the line
`DapperExtensions.DapperExtensions.SqlDialect = new DapperExtensions.Sql.OracleDialect();`
produces the compiler error

> The type or namespace name 'OracleDialect' does not exist in the namespace 'DapperExtensions.Sql' (are you missing an assembly reference?)

When I use the master branch source version, everything works as expected. Is something missing in the Nuget package?

(I am targeting .NET Framework 4.6.2)

**Comment by tmsmith** [comment]
The OracleDialect was not included in the project for 4.5. Corrected with 1.6.1

**Comment by Wintermute79** [comment]
Wow, that was lightning-fast!
:)
Thanks a lot!
