### ISSUE TITLE
How to do a SELECT ... IN?

### ISSUE THREAD

**Issue by k3davis** [tmsmith/Dapper-Extensions#164]
Is there a way to do a SELECT ... IN statement and pass an array of values? This is possible in Dapper proper but I haven't found an example using Dapper-Extensions.

The workaround I've attempted thus far is to create a predicate group of "Or"s for each possible value, but this has seemed to have unreliable results when added to an existing "And" predicate group.

Please forgive if this is mentioned somewhere else - "IN" is a vague term to search by.

**Comment by tmsmith** [comment]
if you use a FieldPredicate, set to Equal and pass in an array it will translate to IN.

https://github.com/tmsmith/Dapper-Extensions/blob/master/DapperExtensions/Predicates.cs#L203
