### ISSUE TITLE
Mapping enum to string

### ISSUE THREAD

**Issue by Wintermute79** [tmsmith/Dapper-Extensions#171]
While mapping enums (numeric values) to numeric db columns works fine, I could not find a good solution to map enums to text columns.

Example:
```
enum Color {
    Red = 1,
    Blue = 2
}
```
should be mapped to an NVARCHAR column that contains the strings "Red" or "Blue".

Is there a convenient way to achieve this?

**Comment by jonathan-bloodworth** [comment]
We've had to write a work around to this which isn't ideal but so far is doing what the original issue is asking. We had to create an extra property on our domain classes which was the string representation of the enum. Our mapper then maps the string representation to the actual database column and ignores the original property. That way our enums are saved as strings and can be parsed again back into their original enum values.

This isn't the best approach and support for configuring enums to be saved as strings would be much appreciated.

```c#
public class User
{
    public StatusEnum Status { get; set; }

    public string StatusValue
    {
        get => Status.ToString();
        set => Status = (StatusEnum)Enum.Parse(typeof(StatusEnum), value);
    }
}

public class UserMapper : ClassMapper<User>
{
    public UserMapper()
    {
        Map(u => u.Status).Ignore();
        Map(u => u.StatusValue).Column("Status");

        AutoMap();
    }
}
```

**Comment by valfrid-ly** [comment]
Enums are basically numbers. Why are you saving them as text? In you example, are you saving "Red", "Blue" or 1, 2??

**Comment by valfrid-ly** [comment]
I think the best way is using your workaround or using https://github.com/ardalis/SmartEnum

I like the SmartEnum also but we also need a workaround
