### ISSUE TITLE
Paging Issue in PostgreSqlDialect (fix included)

### ISSUE THREAD

**Issue by rkiggen** [tmsmith/Dapper-Extensions#191]
Executing a GetPage on a PostgreSql database returns no records when the page is greater than zero.

This is due to a bug in the PostgreSqlDialect  class where in the GetPagingSql method the offset is calculated via the startValue variable:
int startValue = page * resultsPerPage 

and this value is passed as the pageNumber to the GetSetSql method.

However in the GetSetSql method the pageStartRowNbr is set to pageNumber * maxResults instead of using the passed pageNumber argument.

The fix is either 
1. to pass the original page argument from the GetPagingSql method directly to the GetSetSql method 
or 
2. to use the pageNumber for the pageStartRowNbr parameter in the GetSetSql method.

**Fix 1**
Change the GetPagingSql method to:
public override string GetPagingSql(string sql, int page, int resultsPerPage, IDictionary<string, object> parameters)
{
    return GetSetSql(sql, page, resultsPerPage, parameters);
}

**Fix 2**

Change the GetSetSql method to: 
public override string GetSetSql(string sql, int pageNumber, int maxResults, IDictionary<string, object> parameters)
{
    string result = string.Format("{0} LIMIT @maxResults OFFSET @pageStartRowNbr", sql);
    parameters.Add("@maxResults", maxResults);
    parameters.Add("@pageStartRowNbr", pageNumber);
    return result;
}

Good luck,

Rob

**Comment by rkiggen** [comment]
This is already fixed by commit fb371fa31f0051520623a1017868ce5c81e69913

**Comment by maulik-modi** [comment]
@rikiggen, can you please close the issue?
