### ISSUE TITLE
求救！How to use this in MySql ?

### ISSUE THREAD

**Issue by jerryXZW** [tmsmith/Dapper-Extensions#196]
How to use this in MySql 8.0 ?

using Dapper.Extensions.Linq.Builder;
using Dapper.Extensions.Linq.CastleWindsor;
using Dapper.Extensions.Linq.Core.Configuration;
using Dapper.Extensions.Linq.Extensions;
using Dapper.Extensions.Linq.Mapper;
using Dapper.Extensions.Linq.MySql;
using Dapper.Extensions.Linq.Repositories;

 DapperConfiguration
                .Use()
                .UseClassMapper(typeof(AutoClassMapper<>))
                //.UseContainer<Dapper.Extensions.Linq.CastleWindsor.ContainerForWindsor>(c => c.UseExisting(_container))
                .UseSqlDialect(new MySqlDialect())
                //.FromAssembly("WebApplication2.Models")
                .Build();

请问如何使用之前设置它？我试了一整天程序总是报错，都还没有开始真正读取数据库。
现在最主要的问题就是，_container 这个对象是什么？
PS . 我用的是.net core 2.1

How do I set it before using it?I've been trying it all day, and the program is always reporting errors and hasn't even started actually reading the database yet.
Now the main question is, what is the _container object?
PS . I'm using.net core

**Comment by mokezhuhy** [comment]
No net core support currently!

**Comment by niunan** [comment]
看这里。。。
![TIM截图20190501155151](https://user-images.githubusercontent.com/7498393/57009432-1e572f80-6c29-11e9-99cd-5b828fd50032.png)
