### ISSUE TITLE
Int64 Identities - very small change to support them

### ISSUE THREAD

**Issue by jigsawmegs** [tmsmith/Dapper-Extensions#203]
Hi,
Sometimes we need to support Identities that are SQL BigInt and not Int
if you make a small change to the sections where
Convert.ToInt32(identityValue);
is used in the files
DapperAsyncExtensions.cs
and
DapperImplementor.cs
BigInt identity columns are supported.

Just need to test
if (identityColumn.GetType() == typeof(long))
and then take appropriate action
Steve

**Comment by valfrid-ly** [comment]
Same issue here: https://github.com/tmsmith/Dapper-Extensions/issues/201
