### ISSUE TITLE
PostgreSQL problem: '[' in SQL statement

### ISSUE THREAD

**Issue by unipeg** [tmsmith/Dapper-Extensions#205]
When I try to create an entry in PostgreSQL with DapperExtensions using InsertAsync on a PostgreSQL connection, and get this:

`Npgsql.PostgresException : 42601: syntax error at or near "["`

I guess PostgreSQL does not fancy the square brackets the same way that SQL server does.

Any solution to this?

**Comment by NaveenKumar2303** [comment]
I am also facing same issue , any update from your end ?

**Comment by niunan** [comment]
you can add this code, look picture...
![tim 20190102151651](https://user-images.githubusercontent.com/7498393/50582990-8b3c0200-0ea1-11e9-8404-88d4512c5134.png)

**Comment by NaveenKumar2303** [comment]
Thank you niunan , will try the same

**Comment by dealproc** [comment]
This seems to be resolved.  Can we please close it, @NaveenKumar2303 ... unless you are having add'l issues?

**Comment by IAm-Naveen** [comment]
this can be closed

**Comment by rclarke2050** [comment]
this fixed my issue too.
i did not use the SqlMapper approach, nor did I use the SqlMapperExtensions.Insert()

Ive tried on .Net Core 2.1 Lambda, and AWS Aurora 10.7.

Dapper v2.0.30
Dapper.Contrib 2.0.30
DapperExtensions.DotnetCore 1.0.1

**Comment by goforgold** [comment]
Issue solved for me too.

@unipeg  Please close this issue now.

**Comment by eliezeralmeida** [comment]
This not work for me, I did use `DappterExtensions.SqlDialect ` and `DappterExtensions.Configure`. 
I'm using `_context.Connection.GetListAsync`

dotnet project
![image](https://user-images.githubusercontent.com/2786448/133716259-bd285246-624a-404c-ac10-36434aa6b9c1.png)

connection configs
![image](https://user-images.githubusercontent.com/2786448/133716340-d8944e52-c668-44f8-906f-053dc753edee.png)
