### ISSUE TITLE
Oracle Insert Error

### ISSUE THREAD

**Issue by CrazyShaQuiShi** [tmsmith/Dapper-Extensions#215]
Oracle insert error, error code 00928

**Comment by AartBluestoke** [comment]
@CrazyShaQuiShi would you be able to  say what the table structure you were trying into to insert was, and what sql was generated to insert the data?
That error says something about sequences, but that means there may be some type of trigger code running on top of what dapper is trying to do.

Having something repeatable "i am unable to insert values "1,2,'foo' into an oracle 11g database with a table structure of int,int,varchar; and a trigger creating populating column 1 with select ...  " would allow diagnosis of your issue.

**Comment by valfrid-ly** [comment]
Version 1.7.0 implements the support for sequence. Define you key in you mapper as SequenceIdentiy and define the Sequence for it.
