### ISSUE TITLE
DeleteAsync with Predicate does not work

### ISSUE THREAD

**Issue by Boongalow** [tmsmith/Dapper-Extensions#216]
The DeleteAsync code with Predicate cannot work:
`await sqlConnection.DeleteAsync<Data>(predicateGroup).ConfigureAwait(false);`

Will calls (which is correct):
```
public static Task<bool> DeleteAsync<T>( this IDbConnection connection, object predicate, IDbTransaction transaction = null, int? commandTimeout = null)
      where T : class
    {
      return DapperAsyncExtensions.Instance.DeleteAsync<object>(connection, predicate, transaction, commandTimeout);
    }
```
But the implementation is wrong: `DeleteAsync<object>(connection, predicate, transaction, commandTimeout);`

Because object is passed as Type, and Predicate is of type object, that will call (Which is incorrect):
```
public async Task<bool> DeleteAsync<T>( IDbConnection connection, T entity, IDbTransaction transaction, int? commandTimeout)
      where T : class
    {
      IClassMapper classMap = this.SqlGenerator.Configuration.GetMap<T>();
      IPredicate predicate = this.GetKeyPredicate<T>(classMap, entity);
      return await this.DeleteAsync<T>(connection, classMap, predicate, transaction, commandTimeout);
    }
```
Which makes `IPredicate predicate = this.GetKeyPredicate<T>(classMap, entity);` throw an exception obviously.

It should call (but won't because object is passed as T so it chooses the T entity instead):
```
public async Task<bool> DeleteAsync<T>( IDbConnection connection, object predicate, IDbTransaction transaction, int? commandTimeout)
      where T : class
    {
      IClassMapper classMap = this.SqlGenerator.Configuration.GetMap<T>();
      IPredicate wherePredicate = this.GetPredicate(classMap, predicate);
      return await this.DeleteAsync<T>(connection, classMap, wherePredicate, transaction, commandTimeout);
    }
```
Here object predicate must be different from T... but as seen above, object is passed as T so the T entity is chosen.

**Comment by bhukivskyi** [comment]
Hi, I had to fork to fix this problem.
https://github.com/bhukivskyi/Dapper-Extensions
https://www.nuget.org/packages/k1vs.DapperExtensions/

**Comment by Boongalow** [comment]
Hi, thank you for your help. 
But eventually I dropped that extension and created my own.
