### ISSUE TITLE
OracleDialect has issue when always uppercasing column name.

### ISSUE THREAD

**Issue by dotnetprono1** [tmsmith/Dapper-Extensions#217]
I'm not sure if this is not updated with the Oracle DB's behavior.
The column name is really kind of case-sensitive especially when using double quotes around.

So why always force capitalizing the column name as in the code (in OracleDialect.cs)

    public override string QuoteString(string value)
    {
            if (value != null && value[0]=='`')
            {
                return string.Format("{0}{1}{2}", OpenQuote, value.Substring(1, value.Length - 2), CloseQuote);
            }
            return value.ToUpper();
    }

I've had a 2-day blocked issue with this before I had to determine to pull the source code to debug it. All my columns are declared with double quotes already, like this:

    CREATE TABLE "C##CLIENT"."SYSTEM_INFO" 
   (	"Key" NVARCHAR2(450) NOT NULL ENABLE, 
	"Value" NUMBER(1,0) NOT NULL ENABLE)

instead of:

   CREATE TABLE "C##CLIENT"."SYSTEM_INFO" 
   (	Key NVARCHAR2(450) NOT NULL ENABLE, 
	Value NUMBER(1,0) NOT NULL ENABLE)

And when quotes are used, for the created table by the first statement above, some query like this will fail with column written in uppercase (with error like "invalid identifier")

    SELECT "SYSTEM_INFO"."KEY" FROM "SYSTEM_INFO"

and it should be written with the column name exactly maintained (as declared by mapping):

    SELECT "SYSTEM_INFO"."Key" FROM "SYSTEM_INFO"

The code above in `OracleDialect` always turns it to "SYSTEM_INFO"."KEY" and that's why it blocked me for nearly 2 days from working continuously.

Why do you think uppercase column names should always be fine with Oracle? And do it just to make the generated query beautifully formatted?

It's a pity that I have to build my own dll of DapperExtensions (with `ToUpper` removed) or reference the whole source code in my solution, which I always want to avoid.

**Comment by dotnetprono1** [comment]
I had to change the column mapping from:

    Key  -> "Key"

to:

    Key  -> `Key`

So weird, that kind of rule requires you to understand the internal behavior/logic of DapperExtensions.
Now I don't need my own build of DapperExtensions or its reference in my solution.

**Comment by valfrid-ly** [comment]
Oracle is by default case insensitive and use to record everything in uppercase. The only way to do it different is using "". It's not a good pratice to have case sensitive column names as it would allow "ID", "Id" and "iD" columns in the same table and it can be confusing
