### ISSUE TITLE
DapperExtensions for Oracle, selecting only?

### ISSUE THREAD

**Issue by dotnetprono1** [tmsmith/Dapper-Extensions#218]
Have you added support for Oracle with only one thing in mind: support selecting only? Although there are still inserting methods?

I asked this because actually looks like inserting methods are not tested fully, they are failed in case of trying to insert an entity exposing bool properties whose mapped columns having type of NUMBER. 

The underlying Dapper does not support this auto-conversion but some on-top library like DapperExtensions should prepare that.

**It's ridiculous that this simple use case is not tested?**

I can write a simple similar extensions myself within 3 days of working but really I always prefer to not reinventing the wheel.

**Comment by valfrid-ly** [comment]
Check the lastest version. Oracle support is only missing Guid implementation with Raw(16)
