### ISSUE TITLE
Where to apply a custom mapper?

### ISSUE THREAD

**Issue by ghronkrepps** [tmsmith/Dapper-Extensions#222]
I have created a static business data access library that uses dapper & dapper-extensions and created a custom class mapper in order to provide my own table names via a table attribute on my objects. I want to use my library in a web project (ASP.net Web Forms). In order to use my custom mapper in the web project, where would I use this line.

`DapperExtensions.DapperExtensions.DefaultMapper = typeof(MyDapperClassMapper<>);`

**Comment by valfrid-ly** [comment]
Using DefaultMapper you will have only 1 table.

The best way is to register your mappers in the IoC
