### ISSUE TITLE
DapperExtensions.DotNetCore nuget package

### ISSUE THREAD

**Issue by molund** [tmsmith/Dapper-Extensions#223]
Where is the source code for the DapperExtensions.DotNetCore nuget package?  It links back to this repository, but the csproj files here are all for Dotnet Framework.

**Comment by rlreis90** [comment]
The owner for that package is listed as someone else, so I can't tell what that source code is.
That being said, once #226 is merged the source will be here.

**Comment by valfrid-ly** [comment]
From version 1.7.0 onwards the package is compatible with Core and Full Framework
