### ISSUE TITLE
missmatch call in DeleteAsync  

### ISSUE THREAD

**Issue by SassonHW** [tmsmith/Dapper-Extensions#224]
look like it's missing the T generic and calling the wrong DeleteAsync function 

https://github.com/tmsmith/Dapper-Extensions/blob/dd82ecc6f710bca6d5e5645cbff8da97e411257f/DapperExtensions.Net45/DapperAsyncExtensions.cs#L192

**Comment by valfrid-ly** [comment]
With C# 8.0 onwards it's not need anymore as it gets the type from what's in the procedure
