### ISSUE TITLE
DapperExtensions.DotnetCore DbConnection instead of IDbConnection

### ISSUE THREAD

**Issue by The-Running-Dev** [tmsmith/Dapper-Extensions#225]
Not sure this is an issue but the full framework version was using IDbConnection and the .NET core one needs DbConnection. Is this on purpose? Or I'm missing something?

How do I create a generci repository that injects a connection interface?

I am doing this to implement a base repository now:
```
public async Task<TEntity> GetById(long id)
        {
            return await Query(c => ((DbConnection)c).Get<Task<TEntity>>(id));
        }
```

**Comment by rlreis90** [comment]
Related: #226 
When compiling the .NET Framework code to .NET Standard I didn't get any problems, so I'm guessing this will be solved when #226 is merged and everything is IDb.
