### ISSUE TITLE
Any still maintained fork available?

### ISSUE THREAD

**Issue by JMan7777** [tmsmith/Dapper-Extensions#232]
Hi,
Since this project seems to be abandoned, is there any still maintained fork out there which is also providing nuget packages for .net core. 

I found some forks but they are either not .net core compliant or also not well maintained and don't have needed bug fixes implemented. 

Thx.

**Comment by valfrid-ly** [comment]
Sorry... I miss your comment here. I'm maintaining it and we had a recent new release compatible with Net Core and Net 5
