### ISSUE TITLE
Not compatible with .NET 5

### ISSUE THREAD

**Issue by Ibrahim-Islam** [tmsmith/Dapper-Extensions#236]
![image](https://user-images.githubusercontent.com/6401874/107629763-287ade80-6c95-11eb-9061-a1aea9f4870f.png)

**Comment by valfrid-ly** [comment]
I've made a net 5 compatible version in my company. Soon I'll push it to the version I forked from here. I'd like better to have the PR approved here and keep only this official version but...

**Comment by maulik-modi** [comment]
@valfrid-ly , can you push your PR?
@Ibrahim-Islam , Did you manage to resolve it?

**Comment by Ibrahim-Islam** [comment]
I went this SqlKata instead

**Comment by maulik-modi** [comment]
@Ibrahim-Islam , If I am not wrong, SqlKata is only for READ while Dapper-Extensions is for READ/WRITE

**Comment by maulik-modi** [comment]
@valfrid-ly , Is it possible to publish Nuget package of DapperExtensionsDNXCore?

**Comment by valfrid-ly** [comment]
@maulik-modi , I'm a little behing schedule testing and approving the PRs but I also have a version that's multtarget, so doesn't need the DNX to work. But if my memory is not wrong there's a package compatible with net core on nuget.

**Comment by ChiefInnovator** [comment]
I am a little confused as to the current state of DapperExtensions. A customer uses them with .NET 5, but with the errors and warnings that are shown in Visual Studio.  I am intent on recompiling and making a .NET 5 version, but see a bunch of challenges.

1) There seems to be a DapperExtensionsDNXCore in source.  Is this current?
2) There seems to be a DapperExtensions.DotNetCore in NuGet referencing this?  Is that current?  It's publish date is 7 months prior to the current DapperExtensions.

Anything I do I want to align with others working on this.  Is there a .NET 5 version coming soon?

**Comment by valfrid-ly** [comment]
@ChiefInnovator ,

Answering your questions:
1. DNXCore in being deprecated and will be removed from this project. 
2. I don't know this package DapperExtensions.DotNetCore but it seems somebody pushed it and maybe forked from here

About the Net 5 version, it'll coming but I'm still working on getting the pending PRs to the project.

I have my own version that I forked and intend to push here also and that's my goal because I managed to make a single project with a single package that is multi target, so it will be compatible with Net45, Netcore and Net5.

I need some time to finish pushing the PRs and actually looking for a solution on IBM DB2 as IBM remove the packages we used to use from nuget.

**Comment by maulik-modi** [comment]
@valfrid-ly , Can we publish each database in separate project? It is the strategy followed by https://github.com/DbUp/DbUp

**Comment by valfrid-ly** [comment]
For this would take a big effort because the project intends to be generic and support those databases.

I believe it maybe would take longer to be completed and create much more to maintain or even to have a concise code to avoid duplicating it.

**Comment by maulik-modi** [comment]
@valfrid-ly , Is there any plan to release nuget this month?

**Comment by ravimpatel** [comment]
@valfrid-ly  I ran into this awesome library because I didn't want to put dapper contrib attributes in my core layer. Hit a snag because I'm on .net 5. Is this releasing anytime soon?

**Comment by valfrid-ly** [comment]
I published a "New" version while I'm trying to configure the Github actions to publish the official version

**Comment by ravimpatel** [comment]
> I published a "New" version while I'm trying to configure the Github actions to publish the official version
@valfrid-ly, great news, where is this "new" version that you published?

**Comment by valfrid-ly** [comment]
It's on nuget. https://www.nuget.org/packages/DapperExtensions.New

I'll close this issue when I managed to publish the official version.

**Comment by valfrid-ly** [comment]
The official version is now published.
