### ISSUE TITLE
Entity type fix in DapperAsyncExtensions

### ISSUE THREAD

**Issue by JMan7777** [tmsmith/Dapper-Extensions#242]
Can you please also include this entity type fix:

https://github.com/tmsmith/Dapper-Extensions/commit/2a221b9a4cf656d058f2d6b10bb5cb1e14197e86

In my case, without this fix DeleteAsync is not working correctly.
I would like to go back to this original project once it is updated, as I'm currently on the K1vs fork.

Thx a lot.

**Comment by valfrid-ly** [comment]
Just check the next version. It's coming soon
