### ISSUE TITLE
SQLiteException logic error near ".": syntax error

### ISSUE THREAD

**Issue by kelicto** [tmsmith/Dapper-Extensions#244]
Question, see here: https://github.com/tmsmith/Dapper-Extensions/issues/140#issuecomment-841371609
Demo, see here: https://github.com/kelicto/HelloDapper

**Comment by valfrid-ly** [comment]
The answer is the same of this issue with PostgreSQL.

https://github.com/tmsmith/Dapper-Extensions/issues/205
