### ISSUE TITLE
SQL logic error near "FROM": syntax error

### ISSUE THREAD

**Issue by kelicto** [tmsmith/Dapper-Extensions#247]
Using:
```
_helper.Query<FamilyRepSetting>()?.FamilyRepPath;
```
Code:
```
public T Query<T>(Func<T, bool> finder = null) where T : class
{
    DapperExtensions.DapperExtensions.SqlDialect = new SqliteDialect();

    using (IDbConnection connection = new SQLiteConnection(_connectionString))
    {
        connection.Open();

        var data = connection.GetList<T>();

        return finder is null ? data.FirstOrDefault() : data.FirstOrDefault(finder);
    }
}
```

**Comment by valfrid-ly** [comment]
Please provide me some more details like a table structure so it would be possible to replicate

**Comment by kelicto** [comment]
[TestDb.zip](https://github.com/tmsmith/Dapper-Extensions/files/6627696/TestDb.zip)

**Comment by yuancustom** [comment]
### **The similar problem happened to me**

**Comment by kelicto** [comment]
Could you tell me the 'fixed bug' time? Thank you!

**Comment by kelicto** [comment]
All properties must be PUBLIC, INTERNAL will throw this exception. You could make the exception message easy to understand. :) @valfrid-ly
