### ISSUE TITLE
DefaultMapper does not exist

### ISSUE THREAD

**Issue by billjwolff** [tmsmith/Dapper-Extensions#250]
Per  your notes, I tried to add:

DapperExtensions.DapperExtensions.DefaultMapper = typeof(MyCustomClassMapper<>);

For an existing SQL DB with pluralized table names. It says DefaultMapper does not exist. Any ideas?

**Comment by valfrid-ly** [comment]
Can you give me how is it being called or a test code for it?

**Comment by valfrid-ly** [comment]
Not possible to replicate
