### ISSUE TITLE
How to execute 'Table join query'?

### ISSUE THREAD

**Issue by kelicto** [tmsmith/Dapper-Extensions#260]
Does this package support table join queries?

**Comment by valfrid-ly** [comment]
Yes

**Comment by kelicto** [comment]
Could you provide a simple case to show that how to do? Thanks.

**Comment by valfrid-ly** [comment]
You can find a brief explanation here: https://github.com/tmsmith/Dapper-Extensions/issues/252

**Comment by kelicto** [comment]
Thank you!
