### ISSUE TITLE
How can I get Child table's data?

### ISSUE THREAD

**Issue by coderHT** [tmsmith/Dapper-Extensions#264]
I want to join tables using DapperExtensions. But I'm not sure it was support or not. And I don't want to use Stored Procedures.
I only did with Predicate for one table. Following is sample that I want to do.

Parent Table
{
public int Id {get;set;}
public string Name {get;set;}
public int ChildId {get;set;}
public Child child {get;set;}
}

Child Table
{
public int Id {get;set;}
public string ChildName {get;set;}
}

=====================================

Parent List

Id Name     ChildName
1  Sample   SimpleChildName

**Comment by valfrid-ly** [comment]
Did you map your tables? When you create a reference map you're able to join tables and get the child table.

**Comment by coderHT** [comment]
Can I get the reference link, please?

**Comment by valfrid-ly** [comment]
In this test code you can see many different mappings: [Inheritance.cs](https://github.com/tmsmith/Dapper-Extensions/blob/master/DapperExtensions.Test/Data/Common/Inheritance.cs)
