### ISSUE TITLE
AutoMap doesn't work for Id column anymore...?

### ISSUE THREAD

**Issue by k3davis** [tmsmith/Dapper-Extensions#269]
I was surprised and happy today to notice this library had received some updates. There was a breaking change with Predicate namespaces but nothing else was immediately noticeable (I was using an unofficial netstandard build of 1.6.3 previously).

With the update I had to make changes to the mapping for classes that have an Id column.
    
    public AcctDataMapper()
    {
        Table("Acct_Data");
        Map(x => x.Id).Column("Id"); // AutoMap() used to do this but it doesn't work anymore
        Map(x => x.BankName).Ignore();
        Map(x => x.LinkedProfiles).Ignore();
        Map(x => x.LinkedActiveProfiles).Ignore();
        Map(x => x.Status).Ignore();
        AutoMap();
    }
    
I couldn't locate any substantial release notes (maybe I missed them) so perhaps this is already explained somewhere. There are much more elaborate failures than this but this is a more concise example. What change did I miss...?

**Comment by valfrid-ly** [comment]
Could you send me a more complete example of the problem because AutoMap uses Id as default "Key" for the classes if no Key was defined.

**Comment by valfrid-ly** [comment]
If you look in [this test POCO class](https://github.com/tmsmith/Dapper-Extensions/blob/2989ad7cb2f241276ce688ed3e05b320fec4cb56/DapperExtensions.Test/Data/Common/Person.cs#L23) you'll see that it's using AutoMap. 

What I notice in you map is that you actually mapped Id manually and didn't assign any key to it. In this case you're saying to your map that Id is "NotAKey"

**Comment by k3davis** [comment]
I added that line to my map in response to the automap no longer working, as the comment says. Nevertheless i'm not using this library anymore and this issue is rightfully closed. Thanks.
