### ISSUE TITLE
NET Standard 2.0 Warning

### ISSUE THREAD

**Issue by axylophon** [tmsmith/Dapper-Extensions#272]
Hi,

I am using the Dapper Extensions 1.7.0 in a NET Standard 2.0 class library. Unfortunately I get a warning because the Slapper.Automapper package is not targeting 2.0 but only 2.1 and Framework 4.7 instead. Is this a potential issue?

I assume the Slapper.Automapper must also be targeted for 2.0 to remove the warning?

![image](https://user-images.githubusercontent.com/55131237/133437312-bbbaed7b-2df0-49af-bbe7-32e0fbab40ff.png)

Thank you in advance!

**Comment by valfrid-ly** [comment]
Hi, unfortunatelly Slapper doesn't provide netstandard 2.0 or net framework 4.6.1.

It's possible that in the next release the target frameworks have to be upgraded to 4.7 and netstandard 2.1.

For now, except for the warning, I didn't have any concerns with it.

Please, let me know if something didn't work for you.

**Comment by axylophon** [comment]
Thank you for yor response!

We have internal .NET 2.0 Libraries that need to be compatible with Framework 4.7 and .NET 5.
So it would be cool to see a .NET Standard 2.0 target for the Dapper Extensions and Slapper.

.NET Standard 2.1 ist not compatible with Framework so we would also need to multi target our libraries instead. Which could introduce further issues on our side.
