### ISSUE TITLE
Is it possible for dynamic filter using predicates

### ISSUE THREAD

**Issue by matigarowel** [tmsmith/Dapper-Extensions#277]
Ex for dynamic filter:
public async Task < IActionResult > SearchPerson(List<SearchModel> searchModel)
{
	using (SqlConnection cn = new SqlConnection(_connectionString))
	{
		cn.Open();
		var pg = new PredicateGroup { Operator = GroupOperator.And, Predicates = new List<IPredicate>() };
		**foreach(s in searchModel){
			pg.Predicates.Add(Predicates.Field<Person>(f => f[s.Field], s.Operator, s.Value));
		}**
		IEnumerable<Person> list = cn.GetList<Person>(pg);
		cn.Close();
	}
}

**Comment by valfrid-ly** [comment]
This should use your entity as it's the one who has the mapping.

You actually need something like this, without the expression:

```
public async Task < IActionResult > SearchPerson(List searchModel)
{
  using (SqlConnection cn = new SqlConnection(_connectionString))
  {
    cn.Open();
    var pg = new PredicateGroup { Operator = GroupOperator.And, Predicates = new List() };
    pg.Predicates.Add(Predicates.Field<Person>(f => f[s.Field], s.Operator, s.Value));

    foreach(s in searchModel){
    pg.Predicates.Add(Predicates.Field<Person>(f[s.Field], s.Operator, s.Value));
   }
   IEnumerable list = cn.GetList(pg);
   cn.Close();
   }
  }
```

The catch with this is that the name of the property has to match EXACTLY  the name in the object.
