### ISSUE TITLE
sql error

### ISSUE THREAD

**Issue by xtxk110** [tmsmith/Dapper-Extensions#285]
The generated MySQL statement contains [], and an error is reported during execution.
Please try to use ` ` instead

**Comment by ALMMa** [comment]
@xtxk110 I believe you should set the SQL dialect that DapperExtensions will use.

```
DapperExtensions.DapperExtensions.SqlDialect = new DapperExtensions.Sql.MySqlDialect();
```

**Comment by xtxk110** [comment]
> @xtxk110 I believe you should set the SQL dialect that DapperExtensions will use.
> 
> ```
> DapperExtensions.DapperExtensions.SqlDialect = new DapperExtensions.Sql.MySqlDialect();
> ```
> 
> If you already set the dialect, then it's likely a duplicate of #273


have already been solved，thanks
