### ISSUE TITLE
Reference Maps don't appear to use the mapped schema names.

### ISSUE THREAD

**Issue by alongo-tr** [tmsmith/Dapper-Extensions#297]
FWIW, I am unable to query joined tables since the mapped schema name is not prepended to the table name in the join statement. All the other mapped column names are added correctly, and the main table has the schema name prepended.

I don't see a way to add the schema here ...
https://github.com/tmsmith/Dapper-Extensions/blob/a820fb8bd08db8619a32f318f496b6e10a22c379/DapperExtensions/Sql/SqlGenerator.cs#L369

It also seems that the GetTableName function is not being used for the joined tables, just the main table.

**Comment by valfrid-ly** [comment]
Hi @alongo-tr , how are your maps??

I already used joining the same table multiple times and it works but you need to define schema and table name in your map.
