### ISSUE TITLE
Oracle dialect

### ISSUE THREAD

**Issue by ajaydivakaran** [tmsmith/Dapper-Extensions#54]
Is there any implementation of dialect for Oracle?

**Comment by MichaelHaps** [comment]
Can anybody please tell me, why the pull request by fvoronin for Oracle support has not made it into the master?

**Comment by scottluskcis** [comment]
I agree with @MichaelHaps , will (Pull Request)[https://github.com/tmsmith/Dapper-Extensions/pull/64] by fvoronin make it into the trunk at some point or will there be some support for Oracle? I really like a lot of what's available in Dapper.Extensions but do a lot with Oracle databases. Without the support this leaves me having to go other directions.

**Comment by tmsmith** [comment]
lastest
