### ISSUE TITLE
Update fails when Entity has indexed property

### ISSUE THREAD

**Issue by jshurst** [tmsmith/Dapper-Extensions#66]
First of all, awesome work on DapperExtensions.  We ran into an issue the other day with Updates (although might not be limited to updates).  Let's say we have a model that looks like this (we usually have this in a base class).

``` c#
 public class Person
            {                
                public string this[string columnName]
                {
                    get { return "We normally use this for validation"; }
                }
            }
```

In an update when it gets to the ReflectionHelper.GetObjectValues() it will fail on the call to propertyInfo.GetValue(obj, null) with a TargetParameterCountException = {"Parameter count mismatch."}.

I can't think of a situation where we would want to turn an Indexed property into a column name so a quick solution is just to add the following line inside the foreach loop.

``` c#
 if (propertyInfo.GetIndexParameters().Length > 0) continue;
```

Am I doing something wrong (Is this expected behavior)?

Here is a StackOverflow question the deals with iterating over indexed properties: 
 http://stackoverflow.com/questions/4268244/iterating-through-an-indexed-property-reflection

**Comment by JonSnaka** [comment]
Hmmm, actually this still appears not to include the fix. Just ran in to the problem myself.

**Comment by valfrid-ly** [comment]
It's definitively going on next release. Sorry for the 8 years delay!!
