### ISSUE TITLE
ClassMapper ctor: Calling virtual Table() and [not] Schema()

### ISSUE THREAD

**Issue by ghost** [tmsmith/Dapper-Extensions#68]
This is actually two issues that are related...

First: it looks like the ClassMapper constructor is calling virtual Table(). This is actually bad practice, please refer to http://msdn.microsoft.com/en-us/library/ms182331.aspx. I derived a class to do some custom schema naming and the virtual function is called before my ctor has a chance to initialize some values I need.

Second: I noticed the virtual Schema() is never called, so I have to do my Schema property mods in my Table() override.

Suggestion: Call Table() and Schema() at the beginning of ISqlGenerator.GetTableName()

**Comment by valfrid-ly** [comment]
Both of them are changed and going on next release
