### ISSUE TITLE
DapperExtensions including static properties during Update 

### ISSUE THREAD

**Issue by xyanide** [tmsmith/Dapper-Extensions#87]
While updating an object that has static properties Dapper Extensions tries to include the static property with the update.

```
public class Member
{
    public int Id { get; set; }
    public string Firstname { get; set; }

    public static bool IsAuthenticated
    {
        get
        {
            return HttpContext.Current.User.Identity.IsAuthenticated;
        }
    }
}
```

Shouldn't static properties be excluded while updating and inserting?

**Comment by valfrid-ly** [comment]
How is your map? Does it include an Ignore for these properties??

**Comment by valfrid-ly** [comment]
Are you using the latest version?
