### ISSUE TITLE
Could not load file or assembly 'Dapper, Version=1.12.1.1, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified

### ISSUE THREAD

**Issue by milldol1984** [tmsmith/Dapper-Extensions#88]
Hi all, 
I've just installed Dapper Extensions via Nuget. But when I run, the program throws the exception
"Could not load file or assembly 'Dapper, Version=1.12.1.1, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified"
 
Can you give me some suggestions?
Thanks.
MillDol

**Comment by fluxdigital** [comment]
Is this true as surely that is not good application design. I want to keep all references to dapper in my DAL project and not have to add them to my web project. There must be a way of doing this properly?

**Comment by jfaquinojr** [comment]
Any of you guys have a better way of doing this aside from adding the references to UI tier?

**Comment by omersanlier** [comment]
Any commend about this?

**Comment by STIHLFredGuanzon** [comment]
That's how I fixed this error, I just went back into nuget under VS2015 and added checks to the projects needing Dapper and Dapper Extensions.

**Comment by WilliamHBonney** [comment]
Was this closed as by design?  Do you still have to do this?

**Comment by maqk** [comment]
Unacceptable. Somewhere I read to reference the Dapper strongName package. Even that won't resolve my System.IO.FileNotFoundException. Only referring the package in class library consumer resolves
