### ISSUE TITLE
Road Map/Vision for this project.

### ISSUE THREAD

**Issue by phillipsj** [tmsmith/Dapper-Extensions#97]
Hi,

I notice there are several open issues and pull requests.  I know you probably made this project for your own usage, but I would like to help is possible.  Do you have any plans as to what you would like this project to be or not to be? 

Thanks for you time.

Jamie

**Comment by tmsmith** [comment]
DE was started for our latest project and it does what is needed. I try to work on it when time permits but I do not have much time these days. I am willing open it up to more help. I will set you up on the repository.

**Comment by phillipsj** [comment]
I am more than happy to assist, but would like to make sure that in my assistance that I do not take the project in a direction you do not want it to go.  If you are open other directions then I would like others to chime in.

**Comment by tmsmith** [comment]
The original goal of DE was to give a simple ORM with little to no configuration. It has accomplished the original goals. I am not against expanding its features beyond that as long as its original goal of simple and quick configuration and use is maintained.

**Comment by aluanhaddad** [comment]
How about just making the API better. Optional parameters combined with use of `dynamic` and very long argument lists make DapperExtensions hard to learn and easy to misuse.

**Comment by tmsmith** [comment]
I have been looking into what I would like the next version of DE to look like.  Quick hitters: simplified api, better separation of the sql builder, using expressions as part of the predicate, handle anonymous objects / dictionaries in the CRUD methods.

**Comment by aluanhaddad** [comment]
> using expressions as part of the predicate
> handle anonymous objects / dictionaries in the CRUD methods.

These would be a major readability/productivity boosters.

Great news ❤️
