### ISSUE TITLE
Date comparision using Predicate

### ISSUE THREAD

**Issue by thesid** [tmsmith/Dapper-Extensions#98]
How do you compare the date values using predicate group

this is what I have been trying to do

            var predicateGroup = new PredicateGroup { Operator = GroupOperator.And, Predicates = new List<IPredicate>() };
            predicateGroup.Predicates.Add(Predicates.Field<Contents>(f => f.Guid, Operator.Eq, staticContents.Guid));
            predicateGroup.Predicates.Add(Predicates.Field<Contents>(f => f.StartDate, Operator.Ge, DateTime.UtcNow));
            predicateGroup.Predicates.Add(Predicates.Field<Contents>(f => f.EndDate, Operator.Le, DateTime.Now.AddDays(1)));

I am trying to pick the value with a specific GUID and the want it to lie between the required startdate and end date.

I tried the BetweenValue as well but it dosent seem to help.

**Comment by tmsmith** [comment]
did you mean to check your range against 2 different dates in the db.  

you have (guid = @guid and startdate >= @date and enddate <= @date+1)
